[package]
name = "doppler"
authors = ["Blueshift <@blueshift_gg>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }

[dependencies]
# lol = "13.37"

[dev-dependencies]
doppler-sdk = { path = "../sdk" }
mollusk-svm = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true }
solana-program = { workspace = true }
solana-pubkey = { workspace = true }
